services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      GENERIC_TIMEZONE: "Asia/Tehran"
      TZ: "Asia/Tehran"
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"
      N8N_RUNNERS_ENABLED: "true"
      # N8N_SECURE_COOKIE: "false"
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - web-networks
    restart: unless-stopped
    stdin_open: true
    tty: true

volumes:
  n8n_data:


networks:
  web-networks:
    external: true